# Generated by Django 4.2.18 on 2025-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_description_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
