# Generated by Django 4.2.18 on 2025-02-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, default='default_icon.png', upload_to='icons'),
        ),
    ]
