# Generated by Django 4.2.18 on 2025-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, default='icons/default_icon.jpg', upload_to='icons'),
        ),
    ]
