# Generated by Django 4.2.18 on 2025-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Mattermost名を入力ください', max_length=255, unique=True, verbose_name='ユーザー名'),
        ),
    ]
