# Generated by Django 4.2.18 on 2025-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, default='icons/default_icon.jpg', null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_collation='utf8mb4_bin', help_text='Mattermost名を入力ください', max_length=255, unique=True, verbose_name='ユーザー名'),
        ),
    ]
