# Generated by Django 4.2.18 on 2025-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_icon_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, default='https://ahuehurnifer.s3.ap-northeast-1.amazonaws.com/icons/default_icon.jpg', null=True, upload_to='icons/'),
        ),
    ]
