services:
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app/static:/app/static
    depends_on:
      - app
    networks:
      - app_network

  app:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    environment:
      - DJANGO_ENV=production
    volumes:
      - ./app:/app
      - ./app/static:/app/static
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      - db
    networks:
      - app_network

  db:
    container_name: mysql
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "testuser",
          "-ptestuser",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network
      
volumes:
  db_data:

networks:
  app_network:
    driver: bridge
