# Generated by Django 4.2.18 on 2025-02-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.URLField(max_length=255),
        ),
    ]
