# Generated by Django 4.2.18 on 2025-02-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0002_alter_article_url_alter_feed_feed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_at',
            field=models.DateTimeField(),
        ),
    ]
