# Generated by Django 4.2.18 on 2025-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0003_alter_article_posted_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('feed', 'account_name'), name='unique_feed_account'),
        ),
    ]
