# Generated by Django 4.2.18 on 2025-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0007_add_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='site_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='account_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_name',
            field=models.CharField(max_length=32),
        ),
    ]
