# Generated by Django 4.2.18 on 2025-02-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0008_feed_created_at_alter_article_site_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 24, 8, 33, 19, 241333, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
