events {
    worker_connections 1024;  
}

http {
    upstream django {
        server django:8000;
    }

    server {
        listen 80;
        server_name localhost;
        charset utf-8;

        location /static {
            alias /app/static;
        }

        location /techhub/ {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect off;
        }
        server_tokens off;
    }
}



