FROM python:3.10-slim

WORKDIR /app

COPY app/ /app/

COPY ./requirements.txt /app/

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8000

CMD [ "python", "runserver", "manage.py",  "127.0.0.1:8000"]